source 'https://github.com/ipapamagic/IPaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IPaDesignableUI_Example' do
  pod 'IPaDesignableUI', :path => '../'
  

end
